const assert=require('assert/strict'),crypto=require('crypto');const {chromium}=require('playwright');
(async()=>{const b=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream','--disable-features=WebRtcHideLocalIpsWithMdns']});const pages=[];try{
 const password=crypto.randomBytes(24).toString('base64url');const base=process.env.PINGUP_TEST_URL||'http://127.0.0.1:8184/';assert(['localhost','127.0.0.1'].includes(new URL(base).hostname));
 for(let i=0;i<2;i++){const c=await b.newContext({permissions:['microphone','camera'],viewport:{width:1366,height:768}});const guest=await c.request.get(base+'api.php?action=bootstrap').then(r=>r.json());const r=await c.request.post(base+'api.php?action=auth.register',{headers:{'X-CSRF-Token':guest.data.csrf},data:{username:'call'+crypto.randomBytes(5).toString('hex'),name:'Call QA '+i,password}}).then(r=>r.json());assert(r.ok,JSON.stringify(r.error));const p=await c.newPage();p.on('pageerror',e=>console.log('PAGE ERROR',e.message));await p.addInitScript(()=>{const Base=window.RTCPeerConnection;window.RTCPeerConnection=class extends Base{constructor(config){super({...config,iceServers:[]})}};});await p.goto(base);await p.locator('.app-shell').waitFor();pages.push({page:p,user:r.data.user});}
 const [a,c]=pages;for(const kind of ['audio','video']){
 await a.page.locator('[data-page="contacts"]').first().click();await a.page.evaluate(({user,kind})=>window.PingUpCalls.start(user,kind),{user:c.user,kind});
 await c.page.locator('[data-call="accept"]').waitFor({state:'visible',timeout:15000});await c.page.locator('[data-call="accept"]').click();
 await a.page.waitForFunction(()=>document.querySelector('.pu-call-dialog')?.dataset.connected==='true',null,{timeout:20000});await c.page.waitForFunction(()=>document.querySelector('.pu-call-dialog')?.dataset.connected==='true',null,{timeout:20000});await c.page.waitForTimeout(6000);
 const stats=await c.page.evaluate(()=>window.PingUpCalls.getStats());assert(stats.some(row=>row.kind==='audio'&&row.type==='inbound-rtp'&&row.bytesReceived>1000&&row.packetsReceived>20));
 const tracks=await c.page.evaluate(kind=>{const m=document.querySelector(kind==='video'?'.pu-call-remote':'.pu-call-audio');return {audio:m.srcObject.getAudioTracks().length,video:m.srcObject.getVideoTracks().length,paused:m.paused,time:m.currentTime};},kind);assert.equal(tracks.audio,1);if(kind==='video')assert.equal(tracks.video,1);assert(!tracks.paused);assert(tracks.time>2);
 await a.page.bringToFront();await c.page.waitForTimeout(2500);assert.equal(await c.page.locator('.pu-call-dialog').getAttribute('data-connected'),'true');await a.page.evaluate(()=>window.PingUpCalls.end());await c.page.waitForFunction(()=>document.querySelector('.pu-call-dialog')?.dataset.state==='ended');
 console.log('PASS: '+kind+' call, sustained incoming RTP audio, aggregate remote tracks, tab switching (>8s).');}
 }catch(e){for(const item of pages)console.log('CALL DIAGNOSTICS',await item.page.evaluate(async()=>({states:window.PingUpCalls.getDiagnostics(),stats:await window.PingUpCalls.getStats(),status:document.querySelector('#pu-call-status')?.textContent})));throw e;}finally{await b.close();}})().catch(e=>{console.error(e.message);process.exit(1)});
