-- PostgreSQL 15+. Run bin/migrate.php once before serving traffic.


CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE CHECK(username=lower(username)),
    name TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    session_version BIGINT NOT NULL DEFAULT 1,
    role TEXT NOT NULL DEFAULT 'user' CHECK(role IN ('user','admin')),
    bio TEXT NOT NULL DEFAULT '',
    location TEXT NOT NULL DEFAULT '',
    website TEXT NOT NULL DEFAULT '',
    accent TEXT NOT NULL DEFAULT '#a78bfa',
    avatar_file_id BIGINT,
    locale TEXT NOT NULL DEFAULT 'ru' CHECK(locale IN ('ru','uk','en')),
    theme TEXT NOT NULL DEFAULT 'dark' CHECK(theme IN ('dark','light','system')),
    last_seen BIGINT NOT NULL,
    created_at BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL CHECK(type IN ('direct','group','channel','saved')),
    name TEXT NOT NULL DEFAULT '',
    owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    direct_key TEXT UNIQUE,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    slug TEXT UNIQUE,
    invite_token TEXT UNIQUE,
    visibility TEXT NOT NULL DEFAULT 'private' CHECK(visibility IN ('private','public')),
    avatar_file_id BIGINT
);
CREATE TABLE IF NOT EXISTS conversation_members (
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    last_read_message_id BIGINT NOT NULL DEFAULT 0,
    notification_mode TEXT NOT NULL DEFAULT 'all' CHECK(notification_mode IN ('all','mentions','none')),
    pinned BIGINT NOT NULL DEFAULT 0 CHECK(pinned IN (0,1)),
    PRIMARY KEY (conversation_id,user_id)
);
CREATE INDEX IF NOT EXISTS members_user ON conversation_members(user_id,conversation_id);
CREATE TABLE IF NOT EXISTS files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    disk_name TEXT NOT NULL UNIQUE,
    original_name TEXT NOT NULL,
    mime TEXT NOT NULL,
    size BIGINT NOT NULL,
    created_at BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    text TEXT NOT NULL DEFAULT '',
    kind TEXT NOT NULL DEFAULT 'text' CHECK(kind IN ('text','file','voice','call')),
    file_id BIGINT REFERENCES files(id) ON DELETE SET NULL,
    reply_to BIGINT REFERENCES messages(id) ON DELETE SET NULL,
    forwarded_from BIGINT REFERENCES messages(id) ON DELETE SET NULL,
    client_id TEXT NOT NULL,
    pinned BIGINT NOT NULL DEFAULT 0 CHECK(pinned IN (0,1)),
    edited BIGINT NOT NULL DEFAULT 0 CHECK(edited IN (0,1)),
    deleted BIGINT NOT NULL DEFAULT 0 CHECK(deleted IN (0,1)),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    UNIQUE(sender_id,client_id)
);
CREATE INDEX IF NOT EXISTS messages_conversation_id ON messages(conversation_id,id);
CREATE INDEX IF NOT EXISTS messages_conversation_updated ON messages(conversation_id,updated_at);
CREATE TABLE IF NOT EXISTS reactions (
    message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    emoji TEXT NOT NULL,
    PRIMARY KEY(message_id,user_id,emoji)
);
CREATE TABLE IF NOT EXISTS typing (
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at BIGINT NOT NULL,
    PRIMARY KEY(conversation_id,user_id)
);
CREATE TABLE IF NOT EXISTS rate_limits (
    bucket TEXT PRIMARY KEY,
    attempts BIGINT NOT NULL,
    expires_at BIGINT NOT NULL
);


-- Signaling metadata only. Media travels between browsers over encrypted WebRTC.
CREATE TABLE IF NOT EXISTS calls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caller_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    callee_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind TEXT NOT NULL CHECK(kind IN ('audio','video')),
    status TEXT NOT NULL DEFAULT 'ringing' CHECK(status IN ('ringing','active','ended','rejected')),
    created_at BIGINT NOT NULL,
    answered_at BIGINT,
    ended_at BIGINT,
    end_reason TEXT,
    caller_device TEXT NOT NULL DEFAULT '',
    callee_device TEXT NOT NULL DEFAULT '',
    caller_heartbeat BIGINT NOT NULL,
    callee_heartbeat BIGINT NOT NULL,
    CHECK(caller_id <> callee_id)
);
CREATE INDEX IF NOT EXISTS calls_caller ON calls(caller_id,status,id);
CREATE INDEX IF NOT EXISTS calls_callee ON calls(callee_id,status,id);
CREATE TABLE IF NOT EXISTS call_signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    call_id BIGINT NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
    sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK(type IN ('offer','answer','candidate')),
    payload TEXT NOT NULL,
    negotiation BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS call_signals_call ON call_signals(call_id,id);
CREATE UNIQUE INDEX IF NOT EXISTS call_sdp_once ON call_signals(call_id,sender_id,type,negotiation) WHERE type IN ('offer','answer');

CREATE TABLE IF NOT EXISTS notification_settings (
 user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
 settings TEXT NOT NULL DEFAULT '{}'
);
CREATE TABLE IF NOT EXISTS notification_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 kind TEXT NOT NULL CHECK(kind IN ('message','mention','call')),
 message_id BIGINT REFERENCES messages(id) ON DELETE CASCADE,
 call_id BIGINT REFERENCES calls(id) ON DELETE CASCADE,
 dedup_key TEXT NOT NULL,
 created_at BIGINT NOT NULL,
 UNIQUE(user_id,dedup_key)
);
CREATE INDEX IF NOT EXISTS notification_events_user ON notification_events(user_id,id);
CREATE TABLE IF NOT EXISTS push_subscriptions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 endpoint TEXT NOT NULL,
 endpoint_hash TEXT NOT NULL UNIQUE,
 p256dh TEXT NOT NULL,
 auth TEXT NOT NULL,
 session_hash TEXT NOT NULL,
 session_version BIGINT NOT NULL,
 expires_at BIGINT NOT NULL,
 created_at BIGINT NOT NULL,
 updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS push_subscriptions_user ON push_subscriptions(user_id);
CREATE TABLE IF NOT EXISTS push_deliveries (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 event_id BIGINT NOT NULL REFERENCES notification_events(id) ON DELETE CASCADE,
 subscription_id BIGINT NOT NULL REFERENCES push_subscriptions(id) ON DELETE CASCADE,
 status TEXT NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','processing','sent','cancelled','failed')),
 attempts BIGINT NOT NULL DEFAULT 0,
 available_at BIGINT NOT NULL,
 lease_until BIGINT NOT NULL DEFAULT 0,
 error_code TEXT,
 UNIQUE(event_id,subscription_id)
);
CREATE INDEX IF NOT EXISTS push_deliveries_pending ON push_deliveries(status,available_at,lease_until);

ALTER TABLE users ADD CONSTRAINT users_avatar_file_fk FOREIGN KEY(avatar_file_id) REFERENCES files(id) ON DELETE SET NULL;
ALTER TABLE conversations ADD CONSTRAINT conversations_avatar_file_fk FOREIGN KEY(avatar_file_id) REFERENCES files(id) ON DELETE SET NULL;
ALTER TABLE messages ADD COLUMN call_id BIGINT UNIQUE REFERENCES calls(id) ON DELETE SET NULL;
CREATE TABLE message_hidden (
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
 created_at BIGINT NOT NULL,
 PRIMARY KEY(user_id,message_id)
);
CREATE SEQUENCE message_changes_seq;
ALTER TABLE messages ADD COLUMN change_seq BIGINT NOT NULL DEFAULT nextval('message_changes_seq');
CREATE INDEX messages_change_cursor ON messages(conversation_id,change_seq);
CREATE INDEX messages_visible_tail ON messages(conversation_id,id DESC) WHERE deleted=0;
CREATE INDEX messages_file_access ON messages(file_id,conversation_id) WHERE file_id IS NOT NULL AND deleted=0;
CREATE INDEX conversations_public_slug ON conversations(slug) WHERE type='channel' AND visibility='public';
CREATE INDEX calls_cleanup ON calls(status,created_at) WHERE status IN ('ringing','active');
CREATE INDEX rate_limits_expiry ON rate_limits(expires_at);
CREATE INDEX typing_expiry ON typing(expires_at);
CREATE INDEX push_subscription_expiry ON push_subscriptions(expires_at);
CREATE FUNCTION pingup_message_change() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 -- Per-chat lock held until COMMIT: sequence cursor cannot skip a late commit.
 PERFORM pg_advisory_xact_lock(hashtextextended('chat:' || NEW.conversation_id::text,0));
 NEW.change_seq := nextval('message_changes_seq');
 RETURN NEW;
END $$;
CREATE TRIGGER message_change BEFORE INSERT OR UPDATE ON messages FOR EACH ROW EXECUTE FUNCTION pingup_message_change();
CREATE TABLE schema_migrations(version BIGINT PRIMARY KEY,applied_at BIGINT NOT NULL);
INSERT INTO schema_migrations VALUES(4,EXTRACT(EPOCH FROM now())::bigint);

DO $$ DECLARE c record; BEGIN
 FOR c IN SELECT conrelid::regclass AS tbl,conname FROM pg_constraint WHERE contype='f' AND connamespace='public'::regnamespace LOOP
 EXECUTE format('ALTER TABLE %s ALTER CONSTRAINT %I DEFERRABLE INITIALLY IMMEDIATE',c.tbl,c.conname);
 END LOOP;
END $$;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX users_username_search ON users USING gin(username gin_trgm_ops);
CREATE INDEX users_name_search ON users USING gin(name gin_trgm_ops);
CREATE INDEX messages_text_search ON messages USING gin(text gin_trgm_ops) WHERE deleted=0;
CREATE INDEX channels_name_search ON conversations USING gin(name gin_trgm_ops) WHERE type='channel' AND visibility='public';
